### ISSUE TITLE
Chrome 43 (beta) och Firefox >39

### ISSUE THREAD

**Issue by kosmiq** [sebastianekstrom/media-query-detection-with-js#1]
Tjopp.

Använder såklart den här, äntligen, i ett projekt och det fungerade hur fint som helst. Fram till igår då jag fick Chrome 43 beta levererat som uppdatering på Mac:en. Och Firefox 39.nånting mer än innan.

Och dessvärre fungerar det inte riktigt lika bra längre. Eller det som händer är att "breakpoint" nu rapporteras från webbläsaren som antingen (till exempel) "bp-large" (firefox) eller 'bp-large' (Chrome), istället för som tidigare bp-large utan enkla eller dubbla citationstecken runt. Det gör att if(breakpoint === 'bp-large') inte är kompis längre och aldrig matchar. (Den försöker matcha '"bp-large"' mot 'bp-large'.)

Jag gjorde en snabb fulfix med regexp:

``` javascript
$(window).on('breakpoint-change', function(e, breakpoint) {
      breakpoint = breakpoint.replace(/\"/g, '');
      breakpoint = breakpoint.replace(/\'/g, '');
      if(breakpoint === 'bp-small') {
      ...
      }
      ...
});
```

Men det kan säkert göras med ett finare regexp som tar med båda direkt, eller kanske nån annan ändring nånstans.

**Comment by sebastianekstrom** [comment]
Snyggt hittat! Jag kikar på en lösning direkt!
